In [5]:
import pandas as pd

In [ ]:
npr = pd.read_csv('npr.csv')

In [ ]:
npr.head()

In [5]:
#npr['Article'][0]
len(npr)

11992

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english')

In [8]:
dtm = cv.fit_transform(npr['Article'])

In [9]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA = LatentDirichletAllocation(n_components = 7, random_state = 42 )

In [12]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [15]:
len(LDA.components_)

7

In [16]:
LDA.components_.shape

(7, 54777)

In [19]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [21]:
single_topic = LDA.components_[0]

In [24]:
single_topic.argsort() #the argsort() helps to show high probability words

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [25]:
#returns index positions
single_topic.argsort()[-10:] #grabs the 10 greatest values-- last 10 values 

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [26]:
top_ten_words = single_topic.argsort()[-10:]

In [ ]:
#Top 10 words from the first topic

for index in top_ten_words:
    print(cv.get_feature_names_out()[index])

In [ ]:
top_fifteen_words = single_topic.argsort()[-15:]

In [ ]:
#Top 15 words from the first topic
# the words that have the high probability of showing up in the first topic

for index in top_fifteen_words:
    print(cv.get_feature_names_out()[index])

In [18]:
#Grab highest probability words per topic

In [ ]:
for index, topic in enumerate(LDA.components_):
    print(f'The top 15 words for topic #{index}')
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

In [33]:
topic_results = LDA.transform(dtm)

In [34]:
#previously we saw probability of words belonging to a particular topic
#below we have probability of documents belonging to a particular topic

topic_results[0] #implying the very first article at index position 0

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [35]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [36]:
#from above, the first article has the highest probability of belonging to topic 1 at 68%.


In [37]:
topic_results[0].argmax() #returns the index position of the highest probability

1

In [38]:
# assign indext of highest probability topic to the original dataset
npr['Topic'] = topic_results.argmax(axis=1)

In [ ]:
npr